name: eden
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  ably_flutter: ^1.2.29
  cloud_firestore: ^4.17.0
  collection: ^1.18.0
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  github_signin_aksoyhlc:
    git: https://github.com/Becca-Saka/github_signin_aksoyhlc.git
  go_router: ^13.2.4
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  locator: ^0.0.0-dev.2
  mockito: ^5.4.4
  mocktail: ^1.0.3
  plugin_platform_interface: ^2.1.8
  provider: ^6.1.2
  shimmer: ^3.0.0
  skeletonizer: ^1.1.1
  timelines: ^0.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/

  fonts:
    - family: CerebriSans
      fonts:
        - asset: fonts/CerebriSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/CerebriSans-Bold.ttf
          weight: 700
        - asset: fonts/CerebriSans-SemiBold.ttf
          weight: 600
        - asset: fonts/CerebriSans-Medium.ttf
          weight: 500
        - asset: fonts/CerebriSans-Regular.ttf
          weight: 400
        - asset: fonts/CerebriSans-Light.ttf
          weight: 300
